# Generated by Django 4.2.30 on 2026-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel'), ('other', 'Other')], max_length=50)),
                ('ingestion_mode', models.CharField(choices=[('batch', 'Batch Upload'), ('api', 'API Integration')], max_length=20)),
                ('original_file', models.FileField(blank=True, help_text='Retained for auditability', null=True, upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='organizations.organization')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='The exact key-value pairs from the source row/API')),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending Normalization'), ('processed', 'Successfully Processed'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='records.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='e.g., stationary_combustion, purchased_electricity', max_length=100)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_date', models.DateField(help_text='The actual date or start date of the activity')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('normalized_unit', models.CharField(help_text='Standardized unit (e.g., kWh, kg, km)', max_length=50)),
                ('estimated_emissions', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated CO2e in kg', max_digits=19, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Analyst Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('suspicious_reason', models.TextField(blank=True, help_text='Why the system flagged this record', null=True)),
                ('locked_for_audit', models.BooleanField(default=False, help_text='If True, no further edits allowed')),
                ('source_of_truth', models.CharField(help_text='Origin system identifier (e.g., SAP_ERP_01)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='organizations.organization')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='records.rawrecord')),
            ],
            options={
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['organization', 'status'], name='records_nor_organiz_866f9f_idx'), models.Index(fields=['scope', 'category'], name='records_nor_scope_c4ab4c_idx')],
            },
        ),
    ]
