# Generated by Django 4.2.30 on 2026-05-24 15:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='State after the action', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='previous_values',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='State before the action', null=True),
        ),
    ]
